/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/guests': typeof GuestsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/guests': typeof GuestsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/guests': typeof GuestsRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checklist' | '/guests' | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checklist' | '/guests' | '/vendors'
  id: '__root__' | '/' | '/checklist' | '/guests' | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  GuestsRoute: typeof GuestsRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  GuestsRoute: GuestsRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
